### ISSUE TITLE
python, linux, ble.

### ISSUE THREAD

**Issue by RedaBellaf** [Aldiver/rpi-ble#1]
Hello,

I am writing this issue because I am currently using the pycon_ble_demo project just like you.

I saw that you had posted an issue two weeks ago, and I also see that you have made progress in your code 6 hours ago.

I would like to use the python project as you do, but I am stuck at a much more basic step than you.

I have not touched the base code of pycon_ble_demo at all.

I am simply trying to connect to the server and write to the characteristic that was initially created.

My problem is that I am trying to connect using another MacOS PC by using the Bleak library. The problem is that after detecting the Bluetooth server running on another Linux PC, I cannot connect to it.

I would like to know if it would be possible to have your help because I need it for a student project, and I do not understand.

If you have managed to connect to the server and write to the characteristics, your experience would be of great help to me.

This is the scrypt I use to connect to the GATT server.
![image](https://github.com/Aldiver/rpi-ble/assets/104579962/963bf863-483a-434e-92ed-6d0e6482eb9a)

**Comment by Aldiver** [comment]
Hi RedaBellaf,

The error usually appears when connecting to a Bluetooth Device but failed during pairing. In my experience, pairing with the Raspberry Pi requires to type yes to allow pairing and a second yes to accept that the Access Key is the same with the connecting bluetooth device. 

Additionally, it was mentioned by Bruno that for MacOs, you might want to pair the devices first. You can try.
1. Pairing and connecting your Mac to the Linux PC first using the built-in bluetooth settings.
2. In your linux pc, you can try to set the bluetooth sudo nano /etc/bluetooth/main.conf
Look for the keywords Autoconnect, pair or anything you might see useful.
